-- 코드를 입력하세요
SELECT b.PRODUCT_ID, a.PRODUCT_NAME, SUM(b.AMOUNT*a.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT a 
    JOIN FOOD_ORDER b 
    ON a.PRODUCT_ID = b.PRODUCT_ID
        AND b.PRODUCE_DATE LIKE '%2022-05%'
GROUP BY a.PRODUCT_ID, a.PRODUCT_NAME
ORDER BY SUM(b.AMOUNT*a.PRICE) DESC, PRODUCT_ID ASC